# Generated by Django 3.0.4 on 2020-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop_nm', models.CharField(default='', max_length=255, null=True)),
                ('busstop_tp', models.CharField(default='', max_length=255, null=True)),
                ('busstop_seq', models.IntegerField(blank=True, null=True)),
                ('bus_node_id', models.CharField(default='', max_length=255, null=True)),
                ('bus_stop_id', models.CharField(default='', max_length=255, null=True)),
                ('gps_lati', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
                ('route_cd', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('allo_interval', models.CharField(default='', max_length=255, null=True)),
                ('allo_interval_sat', models.CharField(default='', max_length=255, null=True)),
                ('allo_interval_sun', models.CharField(default='', max_length=255, null=True)),
                ('end_node_id', models.CharField(default='', max_length=255, null=True)),
                ('origin_end', models.CharField(default='', max_length=255, null=True)),
                ('origin_end_sat', models.CharField(default='', max_length=255, null=True)),
                ('origin_end_sun', models.CharField(default='', max_length=255, null=True)),
                ('origin_start', models.CharField(default='', max_length=255, null=True)),
                ('origin_start_sat', models.CharField(default='', max_length=255, null=True)),
                ('origin_start_sun', models.CharField(default='', max_length=255, null=True)),
                ('route_cd', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('route_no', models.CharField(default='', max_length=255, null=True)),
                ('route_tp', models.CharField(default='', max_length=255, null=True)),
                ('start_node_id', models.CharField(default='', max_length=255, null=True)),
                ('turn_end', models.CharField(default='', max_length=255, null=True)),
                ('turn_end_sat', models.CharField(default='', max_length=255, null=True)),
                ('turn_end_sun', models.CharField(default='', max_length=255, null=True)),
                ('turn_node_id', models.CharField(default='', max_length=255, null=True)),
                ('turn_start', models.CharField(default='', max_length=255, null=True)),
                ('turn_start_sat', models.CharField(default='', max_length=255, null=True)),
                ('turn_start_sun', models.CharField(default='', max_length=255, null=True)),
                ('start_station_nm', models.CharField(default='', max_length=255, null=True)),
                ('end_station_nm', models.CharField(default='', max_length=255, null=True)),
                ('turn_station_nm', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('busstop_nm', models.CharField(default='', max_length=255, null=True)),
                ('busstop_tp', models.CharField(default='', max_length=255, null=True)),
                ('bus_node_id', models.CharField(default='', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('bus_stop_id', models.CharField(default='', max_length=255)),
                ('gps_lati', models.FloatField(blank=True, null=True)),
                ('gps_long', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
