# Generated by Django 3.0.4 on 2020-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='next_station',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
